### ISSUE TITLE
Support format?

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/gravityblur#1]
Interested not only in supported formats, but also in supported color modes.

**Comment by ilyakurdyukov** [comment]
Which modes? 1,3,4-channels is supported. But for 4-channel only first three is processed, alpha is copied.

**Comment by ilyakurdyukov** [comment]
If you're about RGB and YUV, then YUV is not great here, probably needs different options for Y and UV channels.

**Comment by zvezdochiot** [comment]
Not. I'm talking about palette and gray images.

**Comment by ilyakurdyukov** [comment]
Gray is supported, palette is bad idea here, cause you may need an undithering to proper work of algorithm.

**Comment by zvezdochiot** [comment]
I agree. But you need to specify in README.

**Comment by zvezdochiot** [comment]
⚠️ Not resolved !!!
