### ISSUE TITLE
RIS scheme?

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/gravityblur#2]
Reverse Interpolate Scale (RIS)  (https://github.com/ImageProcessing-ElectronicPublications/gimp-plugin-ris) provides precise scaling multiple. It is of interest to use these schemes (pre-upscale, post-downscale) to obtain smooth contours.

Example gravityblur+HRIS:

* gravityblur (not scale)

![gravityblur](https://i111.fastpic.ru/big/2020/0210/61/6d019546ad26dedda698f48ad6646761.png)

* x2->gravityblur->/2

![gravityblur+HRISx2](https://i111.fastpic.ru/big/2020/0210/cd/f60578a25e201317cd4f2d44687eb5cd.png)

* x3->gravityblur->/3

![gravityblur+HRISx3](https://i111.fastpic.ru/big/2020/0210/f8/39921516991d954414f094463808fef8.png)

**Comment by ilyakurdyukov** [comment]
You want a GIMP plugin?

**Comment by zvezdochiot** [comment]
Not. He is slow. I want inline RIS in your utility.

But can plugin.

**Comment by zvezdochiot** [comment]
⚠️ Not resolved !!!
