### ISSUE TITLE
Args?

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/gravityblur#3]
https://github.com/ilyakurdyukov/gravityblur/blob/a95a50e23d5f31bd6b5ff8b8f8eb43aa299a38c8/main.c#L135
https://github.com/ilyakurdyukov/gravityblur/blob/a95a50e23d5f31bd6b5ff8b8f8eb43aa299a38c8/main.c#L153-L154
https://github.com/ilyakurdyukov/gravityblur/blob/a95a50e23d5f31bd6b5ff8b8f8eb43aa299a38c8/main.c#L170-L177

Maybe?:
```c
		} else if (argc > 2 && !strcmp("--range", arg)) {
			CHECKNUM
			range *= atof(arg2);
			argc -= 2; argv += 2;
		} else if (argc > 2 && !strcmp("--sharp", arg)) {
			CHECKNUM
			sharp *= atof(arg2);
			argc -= 2; argv += 2;
```
`range = kr * range_def`, `sharp = ks * sharp_def`?

**Comment by ilyakurdyukov** [comment]
Не надо придумывать никакого смысла этим параметрам по умолчанию.
Диапазоны: range 0-200, sharp 0-100

**Comment by zvezdochiot** [comment]
Тогда вопрос: Что означают range=0 & sharp=0?

**Comment by ilyakurdyukov** [comment]
На таких значениях не будет никаких изменений.
`range` - это диапазон в котором сглаживаются значения у граничных пикселей, если разница больше диапазона - то не смешиваются вообще. При меньшей разнице смешиваются сильнее, похоже на гравитацию. 100 - это 256, если что, а более 255 разница быть не может, но я немого продолжил, там функция немного меняется, но смысла особого нет дальше продолжать. При нуле ничего не будет меняться.
`sharp` - это сила применения изменений, в принципе должно быть 50. После 100 будут артефакты. Просто можно делать меньше итераций поставив 100. И тут при нуле не будет ничего меняться.

**Comment by ilyakurdyukov** [comment]
`sharp` имеет смысл потому что он не ускоряет итерации. При каждой итерации пиксели успевают повзаимодействовать только с ближайшими соседями, так что радиус эффекта всё равно зависит от количества итеаций. Но `sharp` задаёт силу взаимодействия с соседями.

**Comment by zvezdochiot** [comment]
@ilyakurdyukov say:
>На таких значениях не будет никаких изменений.

Я знаю. На это и указываю. Но в моем "видении"  в твоей "шкале" паметов не только нличествуют бессмысленные значения, но исама "шкала" малопигодна для пользования и во многих случаях неудобнаа.
