### ISSUE TITLE
Color sheme?

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/gravityblur#4]
https://github.com/ilyakurdyukov/gravityblur/blob/a95a50e23d5f31bd6b5ff8b8f8eb43aa299a38c8/main.c#L156-L157
https://github.com/ilyakurdyukov/gravityblur/blob/a95a50e23d5f31bd6b5ff8b8f8eb43aa299a38c8/main.c#L186-L189
https://github.com/ilyakurdyukov/gravityblur/blob/a95a50e23d5f31bd6b5ff8b8f8eb43aa299a38c8/main.c#L213-L214

Maybe?:
```c
			case 'c': arg = "--colorspace"; break;
...
		} else if (!strcmp("--colorspace", arg)) {
			if (!strcmp("YUV", arg2)) {
				type = BITMAP_YUV;
			} else {
				type = BITMAP_RGB;
			}
			argc -= 2; argv += 2;
...
"  -c, --colorspace s         Process in s={RGB,YUV} colorspace\n"
```

**Comment by ilyakurdyukov** [comment]
Вот и правильно, вкусовщиной у себя занимайся.
